name: Update Bounty Listings

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  push:
    paths:
      - 'tracked_repos.json'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-bounties:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Run bounty finder script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scrape/bounty_finder_github_action.py
        
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add bounties/
          git add bounties_by_language/
          git commit -m "Update bounty listings [automated]" || echo "No changes to commit"
          git push
