name: Update Bounty Listings

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  push:  # Run on any push to the repository
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-bounties:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Run bounty finder script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/workflows/scripts/bounty_finder.py
        
      - name: Update README with featured bounties
        run: |
          # Check if featured_bounties.md exists
          if [ -f bounties/featured_bounties.md ]; then
            # Extract content between markers and update README.md
            FEATURED_CONTENT=$(cat bounties/featured_bounties.md)
            # Use sed to replace content between markers in README.md
            sed -i -e '/<!-- BEGIN FEATURED BOUNTIES -->/,/<!-- END FEATURED BOUNTIES -->/c\<!-- BEGIN FEATURED BOUNTIES -->\n'"$FEATURED_CONTENT"'\n<!-- END FEATURED BOUNTIES -->' README.md
          fi
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add bounties/ README.md
          git commit -m "Update bounty listings [automated]" || echo "No changes to commit"
          git push
